/**
 * Full devnet dress rehearsal.
 *
 * Runs the entire launch sequence against devnet with a throwaway token, so
 * that launch day is not the first time these commands have been executed. It
 * creates its own mock holders and influencers, so nothing here depends on the
 * real snapshot.
 *
 * What this DOES prove: the program deploys, the accounts initialize, the
 * Merkle proofs generated by our tooling are accepted on chain, claims pay out,
 * streams open, staking splits base from boost, and the config really does
 * freeze.
 *
 * What this does NOT prove: anything time-dependent. The 30-day and 72-hour
 * windows and the 2030 sweep cannot be exercised on a live chain without
 * waiting. Those are covered by the bankrun integration tests, which fake the
 * clock. Run `npm test` for those.
 *
 *   RPC_URL=https://api.devnet.solana.com KEYPAIR=~/.config/solana/id.json \
 *     npx ts-node scripts/devnet-rehearsal.ts
 */
import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, BN, Program, Wallet } from "@coral-xyz/anchor";
import {
  ACCOUNT_SIZE,
  createAssociatedTokenAccountInstruction,
  createInitializeAccount3Instruction,
  createInitializeMint2Instruction,
  createMintToInstruction,
  getAssociatedTokenAddressSync,
  MINT_SIZE,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  Transaction,
} from "@solana/web3.js";
import * as fs from "fs";
import * as os from "os";
import { buildTree, hashLeaf, MerkleTree } from "./merkle";

const DECIMALS = 6;
const UNIT = 10n ** BigInt(DECIMALS);

const OLD_ALLOC = 550_000n * UNIT;
const INF_ALLOC = 150_000n * UNIT;
const SIGNER_ALLOC = 200_000n * UNIT;
const DEV_ALLOC = 100_000n * UNIT;
const STAKE_TEST = 50_000n * UNIT;
const LOCK_TEST = 10_000n * UNIT;
const TOTAL = OLD_ALLOC + INF_ALLOC + SIGNER_ALLOC + DEV_ALLOC;

/** Placeholder key standing in for the real 2014 one. */
const MOCK_SIGNER_XY = Buffer.alloc(64, 7);

let step = 0;
function heading(text: string) {
  step += 1;
  console.log(`\n${"─".repeat(64)}\n${step}. ${text}\n${"─".repeat(64)}`);
}
function ok(text: string) {
  console.log(`   ✓ ${text}`);
}
function info(text: string) {
  console.log(`     ${text}`);
}

function loadKeypair(pathish: string): Keypair {
  const resolved = pathish.replace(/^~/, os.homedir());
  return Keypair.fromSecretKey(
    Buffer.from(JSON.parse(fs.readFileSync(resolved, "utf8")))
  );
}

async function main() {
  const rpc = process.env.RPC_URL ?? "https://api.devnet.solana.com";
  const connection = new Connection(rpc, "confirmed");
  const payer = loadKeypair(process.env.KEYPAIR ?? "~/.config/solana/id.json");
  const provider = new AnchorProvider(connection, new Wallet(payer), {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  const idl = require("../target/idl/buddy_distributor.json");
  const program = new Program(idl, provider) as Program<any>;
  const account = program.account as any;

  console.log(`\nBUDDY DISTRIBUTOR: DEVNET REHEARSAL`);
  console.log(`rpc:     ${rpc}`);
  console.log(`payer:   ${payer.publicKey.toBase58()}`);
  console.log(`program: ${program.programId.toBase58()}`);

  // -------------------------------------------------------------------------
  heading("Check the program is deployed and the payer is funded");

  const programInfo = await connection.getAccountInfo(program.programId);
  if (!programInfo) {
    throw new Error(
      `Program not found on this cluster.\n` +
        `   Deploy it first:  ~/.avm/bin/anchor-0.31.1 deploy --provider.cluster devnet`
    );
  }
  ok(`program account exists (${programInfo.data.length} bytes)`);

  let balance = await connection.getBalance(payer.publicKey);
  if (balance < 2 * LAMPORTS_PER_SOL) {
    info(`balance is low (${balance / LAMPORTS_PER_SOL} SOL), requesting airdrop…`);
    try {
      const sig = await connection.requestAirdrop(payer.publicKey, 2 * LAMPORTS_PER_SOL);
      await connection.confirmTransaction(sig, "confirmed");
      balance = await connection.getBalance(payer.publicKey);
    } catch {
      throw new Error(
        `Airdrop failed (devnet faucets rate-limit).\n` +
          `   Use https://faucet.solana.com and re-run.`
      );
    }
  }
  ok(`payer holds ${(balance / LAMPORTS_PER_SOL).toFixed(2)} SOL`);

  // The config PDA is global, so a previous rehearsal blocks a fresh one.
  const [configPda] = PublicKey.findProgramAddressSync([Buffer.from("config")], program.programId);
  if (await connection.getAccountInfo(configPda)) {
    throw new Error(
      `A distributor is already initialized at ${configPda.toBase58()}.\n` +
        `   Its config is locked and PDAs cannot be reused, so to rehearse again\n` +
        `   generate a fresh program id:\n` +
        `     solana-keygen new -o target/deploy/buddy_distributor-keypair.json --force\n` +
        `   then update declare_id!/Anchor.toml, rebuild, and redeploy.`
    );
  }

  // -------------------------------------------------------------------------
  heading("Create a mock token (stand-in for the pump.fun mint)");

  const mint = Keypair.generate();
  const mintRent = await connection.getMinimumBalanceForRentExemption(MINT_SIZE);
  await provider.sendAndConfirm(
    new Transaction().add(
      SystemProgram.createAccount({
        fromPubkey: payer.publicKey,
        newAccountPubkey: mint.publicKey,
        space: MINT_SIZE,
        lamports: mintRent,
        programId: TOKEN_PROGRAM_ID,
      }),
      createInitializeMint2Instruction(mint.publicKey, DECIMALS, payer.publicKey, null)
    ),
    [mint]
  );
  ok(`mint ${mint.publicKey.toBase58()}`);

  const treasury = getAssociatedTokenAddressSync(mint.publicKey, payer.publicKey);
  await provider.sendAndConfirm(
    new Transaction().add(
      createAssociatedTokenAccountInstruction(payer.publicKey, treasury, payer.publicKey, mint.publicKey),
      createMintToInstruction(mint.publicKey, treasury, payer.publicKey, TOTAL + STAKE_TEST)
    )
  );
  ok(`minted ${(TOTAL + STAKE_TEST) / UNIT} tokens to the treasury`);
  info(`on launch day this is your dev-buy arriving from pump.fun instead`);

  // -------------------------------------------------------------------------
  heading("Build the Merkle trees (same tooling as the real snapshot)");

  const oldHolders = [
    { kp: Keypair.generate(), amount: (OLD_ALLOC * 60n) / 100n },
    { kp: Keypair.generate(), amount: (OLD_ALLOC * 30n) / 100n },
    { kp: Keypair.generate(), amount: OLD_ALLOC - (OLD_ALLOC * 90n) / 100n },
  ];
  const influencers = [
    { kp: Keypair.generate(), amount: INF_ALLOC / 2n },
    { kp: Keypair.generate(), amount: INF_ALLOC - INF_ALLOC / 2n },
  ];

  const oldTree = buildTree(
    oldHolders.map((h) => ({ address: h.kp.publicKey.toBase58(), amount: h.amount.toString() }))
  ).tree;
  const infTree = buildTree(
    influencers.map((h) => ({ address: h.kp.publicKey.toBase58(), amount: h.amount.toString() }))
  ).tree;

  ok(`old-holder root  ${oldTree.rootHex}`);
  ok(`influencer root  ${infTree.rootHex}`);

  // Fund the mock claimants so they can pay their own transaction fees.
  for (const h of [...oldHolders, ...influencers]) {
    await provider.sendAndConfirm(
      new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: payer.publicKey,
          toPubkey: h.kp.publicKey,
          lamports: 0.02 * LAMPORTS_PER_SOL,
        })
      )
    );
  }
  ok(`funded ${oldHolders.length + influencers.length} mock claimant wallets`);

  // -------------------------------------------------------------------------
  heading("initialize: create the config, pool and vaults");

  const pda = (seed: string, extra?: Buffer) =>
    PublicKey.findProgramAddressSync(
      extra ? [Buffer.from(seed), extra] : [Buffer.from(seed)],
      program.programId
    )[0];

  const poolPda = pda("pool");
  const vaultPda = pda("vault");
  const solVaultPda = pda("sol_vault");
  const devWallet = Keypair.generate();

  await program.methods
    .initialize({
      oldHolderRoot: oldTree.rootArray,
      oldHolderAllocation: new BN(OLD_ALLOC.toString()),
      influencerRoot: infTree.rootArray,
      influencerAllocation: new BN(INF_ALLOC.toString()),
      originalSignerPubkey: Array.from(MOCK_SIGNER_XY),
      originalSignerAllocation: new BN(SIGNER_ALLOC.toString()),
      devWallet: devWallet.publicKey,
      devAllocation: new BN(DEV_ALLOC.toString()),
      devCliffSeconds: new BN(30 * 86400),
      claimsStart: new BN(0),
    })
    .accountsPartial({
      payer: payer.publicKey,
      authority: payer.publicKey,
      rewardMint: mint.publicKey,
      config: configPda,
      pool: poolPda,
      vault: vaultPda,
      solVault: solVaultPda,
      systemProgram: SystemProgram.programId,
      tokenProgram: TOKEN_PROGRAM_ID,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .rpc();
  ok(`config ${configPda.toBase58()}`);
  ok(`vault  ${vaultPda.toBase58()}`);

  // -------------------------------------------------------------------------
  heading("fund_vault: move the committed allocations in");

  await program.methods
    .fundVault(new BN(TOTAL.toString()))
    .accountsPartial({
      authority: payer.publicKey,
      config: configPda,
      vault: vaultPda,
      source: treasury,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .rpc();
  const funded = await connection.getTokenAccountBalance(vaultPda);
  ok(`vault holds ${BigInt(funded.value.amount) / UNIT} tokens`);

  // -------------------------------------------------------------------------
  heading("lock_config, the irreversible one");

  await program.methods
    .lockConfig()
    .accountsPartial({ authority: payer.publicKey, config: configPda, pool: poolPda, vault: vaultPda })
    .rpc();
  ok(`config locked`);

  // Prove the lock actually bites rather than taking it on faith.
  try {
    await program.methods
      .fundVault(new BN(1))
      .accountsPartial({
        authority: payer.publicKey,
        config: configPda,
        vault: vaultPda,
        source: treasury,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();
    throw new Error("FUNDING SUCCEEDED AFTER LOCK. This should be impossible");
  } catch (e: any) {
    if (String(e).includes("should be impossible")) throw e;
    ok(`further funding is rejected (ConfigLocked), so the lock holds`);
  }

  // -------------------------------------------------------------------------
  heading("create_dev_stream: the dev wallet ends up holding nothing");

  await program.methods
    .createDevStream()
    .accountsPartial({
      payer: payer.publicKey,
      config: configPda,
      stream: pda("stream", devWallet.publicKey.toBuffer()),
      systemProgram: SystemProgram.programId,
    })
    .rpc();
  const devStream = await account.stream.fetch(pda("stream", devWallet.publicKey.toBuffer()));
  ok(`${BigInt(devStream.total) / UNIT} tokens streaming to ${devWallet.publicKey.toBase58()}`);
  info(`cliff ${new Date(Number(devStream.cliff) * 1000).toISOString().slice(0, 10)}, ends ${new Date(Number(devStream.end) * 1000).toISOString().slice(0, 10)}`);

  // -------------------------------------------------------------------------
  heading("Old-holder claim: a real Merkle proof accepted on chain");

  const holder = oldHolders[0];
  const holderAta = getAssociatedTokenAddressSync(mint.publicKey, holder.kp.publicKey);
  await provider.sendAndConfirm(
    new Transaction().add(
      createAssociatedTokenAccountInstruction(payer.publicKey, holderAta, holder.kp.publicKey, mint.publicKey)
    )
  );

  const proof = oldTree
    .proofFor(hashLeaf(holder.kp.publicKey.toBase58(), holder.amount))
    .map((p) => Array.from(p));

  await program.methods
    .claimOldHolder(new BN(holder.amount.toString()), proof)
    .accountsPartial({
      claimant: holder.kp.publicKey,
      config: configPda,
      receipt: pda("old_claim", holder.kp.publicKey.toBuffer()),
      vault: vaultPda,
      destination: holderAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    })
    .signers([holder.kp])
    .rpc();

  const received = await connection.getTokenAccountBalance(holderAta);
  ok(`claimed ${BigInt(received.value.amount) / UNIT} tokens, transferred instantly`);

  try {
    await program.methods
      .claimOldHolder(new BN(holder.amount.toString()), proof)
      .accountsPartial({
        claimant: holder.kp.publicKey,
        config: configPda,
        receipt: pda("old_claim", holder.kp.publicKey.toBuffer()),
        vault: vaultPda,
        destination: holderAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([holder.kp])
      .rpc();
    throw new Error("DOUBLE CLAIM SUCCEEDED. This should be impossible");
  } catch (e: any) {
    if (String(e).includes("should be impossible")) throw e;
    ok(`the same wallet cannot claim twice`);
  }

  // -------------------------------------------------------------------------
  heading("Influencer claim: opens a stream instead of paying out");

  const inf = influencers[0];
  await program.methods
    .claimInfluencer(
      new BN(inf.amount.toString()),
      infTree.proofFor(hashLeaf(inf.kp.publicKey.toBase58(), inf.amount)).map((p) => Array.from(p))
    )
    .accountsPartial({
      claimant: inf.kp.publicKey,
      config: configPda,
      receipt: pda("inf_claim", inf.kp.publicKey.toBuffer()),
      stream: pda("stream", inf.kp.publicKey.toBuffer()),
      systemProgram: SystemProgram.programId,
    })
    .signers([inf.kp])
    .rpc();

  const infStream = await account.stream.fetch(pda("stream", inf.kp.publicKey.toBuffer()));
  ok(`${BigInt(infStream.total) / UNIT} tokens streaming over 30 days, nothing paid up front`);

  // -------------------------------------------------------------------------
  heading("Staking: a flexible position plus a separate lockup entity");

  const staker = Keypair.generate();
  await provider.sendAndConfirm(
    new Transaction().add(
      SystemProgram.transfer({
        fromPubkey: payer.publicKey,
        toPubkey: staker.publicKey,
        lamports: 0.05 * LAMPORTS_PER_SOL,
      })
    )
  );
  const stakerAta = getAssociatedTokenAddressSync(mint.publicKey, staker.publicKey);
  await provider.sendAndConfirm(
    new Transaction().add(
      createAssociatedTokenAccountInstruction(payer.publicKey, stakerAta, staker.publicKey, mint.publicKey),
      createMintToInstruction(mint.publicKey, stakerAta, payer.publicKey, STAKE_TEST + LOCK_TEST)
    )
  );

  // Flexible: no tier argument any more, weight == amount, exit gated only by
  // the 24-hour unstake cooldown.
  await program.methods
    .stake(new BN(STAKE_TEST.toString()))
    .accountsPartial({
      owner: staker.publicKey,
      config: configPda,
      pool: poolPda,
      position: pda("stake", staker.publicKey.toBuffer()),
      vault: vaultPda,
      source: stakerAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    })
    .signers([staker])
    .rpc();
  ok(`staked ${STAKE_TEST / UNIT} tokens flexible (1.0x, weight == amount)`);

  // Locked principal lives in its own account per lock, addressed by an index
  // that must match the wallet's counter. Tier 3 = 5 months at 5.0x, so four
  // fifths of whatever this lockup earns is boost held in escrow to maturity.
  const lockupIndex = 0;
  const lockupIndexLe = Buffer.alloc(8); // u64 LE of lockupIndex
  const lockupPda = PublicKey.findProgramAddressSync(
    [Buffer.from("lockup"), staker.publicKey.toBuffer(), lockupIndexLe],
    program.programId
  )[0];
  const lockupCounterPda = PublicKey.findProgramAddressSync(
    [Buffer.from("lockup_count"), staker.publicKey.toBuffer()],
    program.programId
  )[0];

  await program.methods
    .lockTokens(new BN(LOCK_TEST.toString()), 3, new BN(lockupIndex))
    .accountsPartial({
      owner: staker.publicKey,
      config: configPda,
      pool: poolPda,
      counter: lockupCounterPda,
      lockup: lockupPda,
      vault: vaultPda,
      source: stakerAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    })
    .signers([staker])
    .rpc();
  ok(`locked ${LOCK_TEST / UNIT} tokens at the 5-month 5.0x tier (lockup #${lockupIndex})`);

  const rewardAmount = 10_000n * UNIT;
  await provider.sendAndConfirm(
    new Transaction().add(
      createMintToInstruction(mint.publicKey, treasury, payer.publicKey, rewardAmount)
    )
  );
  await program.methods
    .notifyTokenRewards(new BN(rewardAmount.toString()))
    .accountsPartial({
      depositor: payer.publicKey,
      config: configPda,
      pool: poolPda,
      vault: vaultPda,
      source: treasury,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .rpc();
  ok(`deposited ${rewardAmount / UNIT} tokens of rewards into bucket 1`);

  const before = BigInt((await connection.getTokenAccountBalance(stakerAta)).value.amount);
  await program.methods
    .claimRewards()
    .accountsPartial({
      owner: staker.publicKey,
      config: configPda,
      pool: poolPda,
      position: pda("stake", staker.publicKey.toBuffer()),
      vault: vaultPda,
      solVault: solVaultPda,
      destination: stakerAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([staker])
    .rpc();

  const paid = BigInt((await connection.getTokenAccountBalance(stakerAta)).value.amount) - before;
  ok(`flexible position claimed ${paid / UNIT} tokens, all of it base (1.0x holds no escrow)`);

  const lockBefore = BigInt((await connection.getTokenAccountBalance(stakerAta)).value.amount);
  await program.methods
    .claimLockupRewards()
    .accountsPartial({
      owner: staker.publicKey,
      config: configPda,
      pool: poolPda,
      lockup: lockupPda,
      vault: vaultPda,
      solVault: solVaultPda,
      destination: stakerAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([staker])
    .rpc();

  const lockPaid = BigInt((await connection.getTokenAccountBalance(stakerAta)).value.amount) - lockBefore;
  const lockup = await account.lockup.fetch(lockupPda);
  ok(`lockup claimed ${lockPaid / UNIT} as base (the 1.0x share)`);
  ok(`held back ${BigInt(lockup.escrowToken) / UNIT} as boost, escrowed until maturity`);

  // Demotion is the permissionless crank that releases a matured lock's
  // escrow and cuts it back to 1x. Prove it cannot fire early.
  try {
    await program.methods
      .demoteMatured()
      .accountsPartial({
        cranker: payer.publicKey,
        config: configPda,
        pool: poolPda,
        lockup: lockupPda,
      })
      .rpc();
    throw new Error("DEMOTED BEFORE MATURITY. This should be impossible");
  } catch (e: any) {
    if (String(e).includes("should be impossible")) throw e;
    ok(`the lock cannot be demoted before it matures (EscrowNotMatured)`);
  }

  // -------------------------------------------------------------------------
  heading("Sync: value that arrives from outside the program");

  // This is how pump.fun creator fees reach stakers, and how a donation sent
  // straight to the published vault address is rescued rather than frozen.
  const gift = 0.05 * LAMPORTS_PER_SOL;
  await provider.sendAndConfirm(
    new Transaction().add(
      SystemProgram.transfer({
        fromPubkey: payer.publicKey,
        toPubkey: solVaultPda,
        lamports: gift,
      })
    )
  );

  let poolNow = await account.stakePool.fetch(poolPda);
  const beforeSync = BigInt(poolNow.lifetimeSolRewards);
  ok(`sent ${gift / LAMPORTS_PER_SOL} SOL straight to the vault`);
  info(`ledger still shows ${beforeSync} lamports of rewards, because it cannot see it`);

  await program.methods
    .syncSolRewards()
    .accountsPartial({
      config: configPda,
      pool: poolPda,
      solVault: solVaultPda,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .rpc();

  poolNow = await account.stakePool.fetch(poolPda);
  const afterSync = BigInt(poolNow.lifetimeSolRewards);
  ok(`after sync the ledger shows ${afterSync}, having credited ${afterSync - beforeSync}`);
  info(`anyone can call this; it needs no signer beyond whoever pays the fee`);

  // -------------------------------------------------------------------------
  heading("Rehearsal complete");

  const finalConfig = await account.config.fetch(configPda);
  const finalPool = await account.stakePool.fetch(poolPda);

  console.log(`
  config          ${configPda.toBase58()}
  vault           ${vaultPda.toBase58()}
  mock mint       ${mint.publicKey.toBase58()}
  locked          ${finalConfig.locked}
  old claimed     ${BigInt(finalConfig.oldHolderClaimed) / UNIT} / ${BigInt(finalConfig.oldHolderAllocation) / UNIT}
  inf claimed     ${BigInt(finalConfig.influencerClaimed) / UNIT} / ${BigInt(finalConfig.influencerAllocation) / UNIT}
  total staked    ${BigInt(finalPool.totalStaked) / UNIT}
  lifetime rewards ${BigInt(finalPool.lifetimeTokenRewards) / UNIT}

  Inspect it: https://explorer.solana.com/address/${configPda.toBase58()}?cluster=devnet

  Point the app at it:
    cd app
    VITE_RPC_URL=https://api.devnet.solana.com VITE_PROGRAM_ID=${program.programId.toBase58()} npm run dev

  Not covered here (needs a fake clock, see the bankrun tests via 'npm test'):
    - the 30-day and 72-hour windows expiring
    - the three sweeps moving remainders into bucket 1
    - emergency exit forfeiting boost + 15%
    - the 2030 original-signer deadline

  Not covered here at all (pump.fun has no devnet): the creator-fee chain.
  See docs/DEVNET-REHEARSAL.md, "The one part that cannot be rehearsed here".
`);
}

main().catch((e) => {
  console.error(`\n✗ ${e.message ?? e}\n`);
  process.exit(1);
});
